export { default as compareKeys } from './compareKeys'
export { default as escape } from './escape'
export { default as extend } from './extend'
export { default as isIdentifier } from './isIdentifier'
export * from './isProxy'
export { default as objectName } from './objectName'
